### ISSUE TITLE
한글 번역이 한글로 나오는 이슈

### ISSUE THREAD

**Issue by kkangil** [jojoldu/translator#18]
네이버 API 를 사용하는 방식으로 등록하여 사용중입니다.

한글 -> 한글, 영어 -> 영어 로 번역이 되어 나오는데 혹시 어떤 설정을 해줘야 하는지 알고 계신가요??

<img width="397" alt="image" src="https://user-images.githubusercontent.com/29226051/87397121-c36fe500-c5ee-11ea-93df-ae1e7814b711.png">

<img width="207" alt="image" src="https://user-images.githubusercontent.com/29226051/87397141-cb2f8980-c5ee-11ea-84e8-273dc854d824.png">

<img width="215" alt="image" src="https://user-images.githubusercontent.com/29226051/87397168-d7b3e200-c5ee-11ea-9b59-7516ddc81f63.png">

**Comment by namioto** [comment]
더이상 네이버와 제대로 연동되지 않는 것으로 보입니다.

**Comment by jojoldu** [comment]
@namioto @kkangil 안녕하세요! 
대체제 플러그인을 발견하게 되어서 ㅠ (특히 기본 사용 API인 MS 번역 API가 무료사용량을 초과하기도해서 ㅠ)
더이상 이 플러그인 개선을 진행하지 않으려고 합니다

* https://plugins.jetbrains.com/plugin/8579-translation

위 플러그인으로 대체해서 사용하시는것을 추천드립니다!
