### ISSUE TITLE
Translate the Github page in English

### ISSUE THREAD

**Issue by Kendos-Kenlen** [jojoldu/translator#5]
Hi,

I'm not a native Korean speaker (nor a Korean speaker at all for the moment) but I'll learn Korean soon when I'll be there.

I think this plugin could help me to learn words and practice (after all, why should I code in english when in Korea if Korean coding could help me practising ?). However the whole readme and commit history is in Korean. Could you add an english section or a translation of the readme at least ?

Thanks ! :)

**Comment by jojoldu** [comment]
Hi Kendos-Kenlen,
English guide was added.
I look forward to your interest and issues in the future.
Thanks
