### ISSUE TITLE
Support version 2017.2 (172.*)

### ISSUE THREAD

**Issue by Kendos-Kenlen** [jojoldu/translator#8]
Hi,

The public preview has been released recently, but when I try to install the plugin (by installing from disk), I have the error "this plugin is not compatible with your installation".
It is also not visible from plugin browser inside IntelliJ.

Maximum version should be upgraded.

**Comment by jojoldu** [comment]
Hi
Thanks for the issue.
I have not checked the 2017.2 upgrade yet.

Thanks

**Comment by jojoldu** [comment]
Hi Kendos-Kenlen 
I'll tell you I'm sorry first.
A bug in Jetbrains is causing the version change to continue.
I decided to change the value of DB directly from Jetbrains.
wait a munite

Below is a reply from Jetbrains.

```
Hi,

I'm sorry for a delay. It does not matter where you are. It's a bug on our side - the value does not change, we can change it in the database or you can change it in the plugin.xml and upload a new version.

Thank you!

Regards,
Mikhail Vink
```

**Comment by Kendos-Kenlen** [comment]
Hi,

Okay, hope it'll allow me to install the plugin !

Thank you :)

**Comment by jojoldu** [comment]
Hi Kendos-Kenlen
The version bug has finally been fixed!
It will now be compatible between 2017.1 and 2018.1.
2017.3 RC2 came out and I tested it and it works well
Thank you for waiting so long.
